
CREATE DATABASE IF NOT EXISTS StuGate CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;


USE StuGate;

CREATE TABLE SinhVien (
    maSV VARCHAR(50) PRIMARY KEY,
    hoTen NVARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    matKhau VARCHAR(255) NOT NULL,
    soDienThoai VARCHAR(15),
    diaChi NVARCHAR(255),
    diemGPA DECIMAL(4, 2)
) ENGINE=InnoDB;

CREATE TABLE GiangVien (
    maGV VARCHAR(50) PRIMARY KEY,
    hoTen NVARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    matKhau VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE QuanLy (
    maQL VARCHAR(50) PRIMARY KEY,
    hoTen NVARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    matKhau VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE MonHoc (
    maMH VARCHAR(50) PRIMARY KEY,
    tenMH NVARCHAR(150) NOT NULL,
    soTinChi INT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE LichHoc (
    maLichHoc VARCHAR(50) PRIMARY KEY,
    thuTrongTuan INT NOT NULL,
    tietHoc VARCHAR(50) NOT NULL,
    phongHoc VARCHAR(50)
) ENGINE=InnoDB;

CREATE TABLE LopHoc (
    maLop VARCHAR(50) PRIMARY KEY,
    tenLop NVARCHAR(150),
    hocKy VARCHAR(50) NOT NULL,
    maGV VARCHAR(50),
    maLichHoc VARCHAR(50),
    maMH VARCHAR(50),
    FOREIGN KEY (maGV) REFERENCES GiangVien(maGV) ON DELETE SET NULL,
    FOREIGN KEY (maLichHoc) REFERENCES LichHoc(maLichHoc) ON DELETE SET NULL,
    FOREIGN KEY (maMH) REFERENCES MonHoc(maMH) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE DangKyHoc (
    maSV VARCHAR(50),
    maLop VARCHAR(50),
    PRIMARY KEY (maSV, maLop),
    FOREIGN KEY (maSV) REFERENCES SinhVien(maSV) ON DELETE CASCADE,
    FOREIGN KEY (maLop) REFERENCES LopHoc(maLop) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Diem (
    maSV VARCHAR(50),
    maLop VARCHAR(50),
    diemThanhPhan DECIMAL(4, 2),
    diemCuoiKy DECIMAL(4, 2),
    diemTongKet DECIMAL(4, 2),
    PRIMARY KEY (maSV, maLop),
    FOREIGN KEY (maSV, maLop) REFERENCES DangKyHoc(maSV, maLop) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE TaiLieu (
    maTaiLieu INT AUTO_INCREMENT PRIMARY KEY,
    tenFile VARCHAR(255) NOT NULL,
    duongDan VARCHAR(255) NOT NULL,
    ngayTaiLen DATETIME DEFAULT CURRENT_TIMESTAMP,
    maLop VARCHAR(50),
    FOREIGN KEY (maLop) REFERENCES LopHoc(maLop) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ThongBao (
    maThongBao INT AUTO_INCREMENT PRIMARY KEY,
    tieuDe NVARCHAR(255) NOT NULL,
    noiDung TEXT,
    ngayGui DATETIME DEFAULT CURRENT_TIMESTAMP,
    maLop VARCHAR(50),
    FOREIGN KEY (maLop) REFERENCES LopHoc(maLop) ON DELETE CASCADE
) ENGINE=InnoDB;